-- AlterTable
ALTER TABLE `devices` ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `lastSeen` DATETIME(3) NULL,
    ADD COLUMN `status` ENUM('ONLINE', 'OFFLINE', 'WARNING', 'ERROR') NOT NULL DEFAULT 'ONLINE';
